const selectOptions = {
  gender: [
    { name: "Male", value: "Male" },
    { name: "Female", value: "Female" },
  ],
  bloodType: [
    { name: "A+", value: "A+" },
    { name: "A-", value: "A-" },
    { name: "B+", value: "B+" },
    { name: "B-", value: "B-" },
    { name: "AB+", value: "AB+" },
    { name: "AB-", value: "AB-" },
    { name: "O+", value: "O+" },
    { name: "O-", value: "O-" },
  ],
  medicalSpecialties: [
    { name: "General Medicine", value: "General Medicine" },
    { name: "Surgery", value: "Surgery" },
    { name: "Family Medicine", value: "Family Medicine" },
    { name: "Internal Medicine", value: "Internal Medicine" },
    { name: "Pediatrics", value: "Pediatrics" },
    { name: "Obstetrics and Gynecology", value: "Obstetrics and Gynecology" },
    { name: "Psychiatry", value: "Psychiatry" },
    { name: "Ophthalmology", value: "Ophthalmology" },
    { name: "Otolaryngology", value: "Otolaryngology" },
    { name: "Neurology", value: "Neurology" },
    { name: "Cardiology", value: "Cardiology" },
    { name: "Gastroenterology", value: "Gastroenterology" },
    { name: "Endocrinology", value: "Endocrinology" },
    { name: "Pulmonology", value: "Pulmonology" },
    { name: "Oncology", value: "Oncology" },
    { name: "Orthopedics", value: "Orthopedics" },
    { name: "Dermatology", value: "Dermatology" },
    { name: "Infectious Diseases", value: "Infectious Diseases" },
    { name: "Emergency Medicine", value: "Emergency Medicine" },
    { name: "Anesthesiology", value: "Anesthesiology" },
    { name: "Allergy and Immunology", value: "Allergy and Immunology" },
    { name: "Hematology", value: "Hematology" },
    { name: "Nephrology", value: "Nephrology" },
    { name: "Rheumatology", value: "Rheumatology" },
    { name: "Physical Medicine and Rehabilitation", value: "Physical Medicine and Rehabilitation" },
    { name: "Sports Medicine", value: "Sports Medicine" },
    { name: "Pain Medicine", value: "Pain Medicine" },
    { name: "Sleep Medicine", value: "Sleep Medicine" },
    { name: "Geriatrics", value: "Geriatrics" },
    { name: "Palliative Care", value: "Palliative Care" },
    { name: "Addiction Medicine", value: "Addiction Medicine" },
    { name: "Infectious Disease Control", value: "Infectious Disease Control" },
    { name: "Public Health and Preventive Medicine", value: "Public Health and Preventive Medicine" },
    { name: "Medical Genetics", value: "Medical Genetics" },
    { name: "Forensic Medicine", value: "Forensic Medicine" },
    { name: "Nuclear Medicine", value: "Nuclear Medicine" },
    { name: "Radiology", value: "Radiology" },
    { name: "Pathology", value: "Pathology" },
    { name: "Emergency Medical Services", value: "Emergency Medical Services" },
    { name: "Aerospace Medicine", value: "Aerospace Medicine" },
  ],
  medicalSpecialty: [
    { name: "General Medicine", value: "General Medicine" },
    { name: "Surgery", value: "Surgery" },
    { name: "Family Medicine", value: "Family Medicine" },
    { name: "Internal Medicine", value: "Internal Medicine" },
    { name: "Pediatrics", value: "Pediatrics" },
    { name: "Obstetrics and Gynecology", value: "Obstetrics and Gynecology" },
    { name: "Psychiatry", value: "Psychiatry" },
    { name: "Ophthalmology", value: "Ophthalmology" },
    { name: "Otolaryngology", value: "Otolaryngology" },
    { name: "Neurology", value: "Neurology" },
    { name: "Cardiology", value: "Cardiology" },
    { name: "Gastroenterology", value: "Gastroenterology" },
    { name: "Endocrinology", value: "Endocrinology" },
    { name: "Pulmonology", value: "Pulmonology" },
    { name: "Oncology", value: "Oncology" },
    { name: "Orthopedics", value: "Orthopedics" },
    { name: "Dermatology", value: "Dermatology" },
    { name: "Infectious Diseases", value: "Infectious Diseases" },
    { name: "Emergency Medicine", value: "Emergency Medicine" },
    { name: "Anesthesiology", value: "Anesthesiology" },
    { name: "Allergy and Immunology", value: "Allergy and Immunology" },
    { name: "Hematology", value: "Hematology" },
    { name: "Nephrology", value: "Nephrology" },
    { name: "Rheumatology", value: "Rheumatology" },
    { name: "Physical Medicine and Rehabilitation", value: "Physical Medicine and Rehabilitation" },
    { name: "Sports Medicine", value: "Sports Medicine" },
    { name: "Pain Medicine", value: "Pain Medicine" },
    { name: "Sleep Medicine", value: "Sleep Medicine" },
    { name: "Geriatrics", value: "Geriatrics" },
    { name: "Palliative Care", value: "Palliative Care" },
    { name: "Addiction Medicine", value: "Addiction Medicine" },
    { name: "Infectious Disease Control", value: "Infectious Disease Control" },
    { name: "Public Health and Preventive Medicine", value: "Public Health and Preventive Medicine" },
    { name: "Medical Genetics", value: "Medical Genetics" },
    { name: "Forensic Medicine", value: "Forensic Medicine" },
    { name: "Nuclear Medicine", value: "Nuclear Medicine" },
    { name: "Radiology", value: "Radiology" },
    { name: "Pathology", value: "Pathology" },
    { name: "Emergency Medical Services", value: "Emergency Medical Services" },
    { name: "Aerospace Medicine", value: "Aerospace Medicine" },
  ],
  diseases: [
    { name: "Coronary artery disease", value: "Coronary artery disease" },
    { name: "Stroke", value: "Stroke" },
    { name: "Lower respiratory infections", value: "Lower respiratory infections" },
    { name: "Chronic obstructive pulmonary disease (COPD)", value: "Chronic obstructive pulmonary disease (COPD)" },
    { name: "Lung cancer", value: "Lung cancer" },
    { name: "Alzheimer's disease and dementia", value: "Alzheimer's disease and dementia" },
    { name: "Diarrheal diseases", value: "Diarrheal diseases" },
    { name: "Diabetes mellitus", value: "Diabetes mellitus" },
    { name: "Kidney disease", value: "Kidney disease" },
    { name: "Liver disease", value: "Liver disease" },
    { name: "Tuberculosis (TB)", value: "Tuberculosis (TB)" },
    { name: "HIV/AIDS", value: "HIV/AIDS" },
    { name: "Malaria", value: "Malaria" },
    { name: "Measles", value: "Measles" },
    { name: "Hepatitis B and C", value: "Hepatitis B and C" },
    { name: "Parkinson's disease", value: "Parkinson's disease" },
    { name: "Breast cancer", value: "Breast cancer" },
    { name: "Prostate cancer", value: "Prostate cancer" },
    { name: "Cervical cancer", value: "Cervical cancer" },
    { name: "Colorectal cancer", value: "Colorectal cancer" },
    { name: "Influenza (flu)", value: "Influenza (flu)" },
    { name: "Asthma", value: "Asthma" },
    { name: "Arthritis", value: "Arthritis" },
    { name: "Osteoporosis", value: "Osteoporosis" },
    { name: "Depression", value: "Depression" },
    { name: "Anxiety disorders", value: "Anxiety disorders" },
    { name: "Schizophrenia", value: "Schizophrenia" },
    { name: "Bipolar disorder", value: "Bipolar disorder" },
    { name: "Eating disorders", value: "Eating disorders" },
    { name: "Cardiovascular disease", value: "Cardiovascular disease" },
    { name: "Hypertension (high blood pressure)", value: "Hypertension (high blood pressure)" },
    { name: "Chronic kidney disease", value: "Chronic kidney disease" },
    { name: "Chronic liver disease", value: "Chronic liver disease" },
    { name: "Chronic pain", value: "Chronic pain" },
    { name: "Chronic fatigue syndrome", value: "Chronic fatigue syndrome" },
    { name: "Fibromyalgia", value: "Fibromyalgia" },
    { name: "Multiple sclerosis", value: "Multiple sclerosis" },
    { name: "Rheumatoid arthritis", value: "Rheumatoid arthritis" },
    { name: "Psoriasis", value: "Psoriasis" },
    { name: "Eczema", value: "Eczema" },
  ],
};

export default selectOptions;
